def chat_bot_response(input_text: str) -> str:
    """
    This method handles the calling to specific chat
    and its responses

    Args:
        input_text (str): The user prompt

    Returns:
        str: The response generated by the chatbot model
    """
    return f"You said: '{input_text}'"